[package]
  name = "recordwebskocet"
  version = "0.1.0"
  edition = "2021"

  [dependencies]
  ipgeolocate = "0.3.3"
  reqwest = { version = "0.12", features = ["json", "blocking"] }
  tokio = { version = "1", features = ["full"] }
  serde = { version = "1.0", features = ["derive"] }